Repository UnimibSoftEngCourse2022/progetto-questionari-1-dev-team, pull requests merged in 2022-01, with the labels that each got.

#21 Implementation Category
  src/main/java/it/unimib/unimibmodules/controller/CategoryController.java
  src/main/java/it/unimib/unimibmodules/dao/CategoryDAO.java
  src/main/java/it/unimib/unimibmodules/exception/EmptyCategoryException.java
  src/main/java/it/unimib/unimibmodules/model/Category.java
  src/main/java/it/unimib/unimibmodules/repository/CategoryRepository.java
  src/main/java/it/unimib/unimibmodules/repository/Repository.java
Labels: enhancement

#22 Implementation Question
  .gitignore
  pom.xml
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/dao/QuestionDAO.java
  src/main/java/it/unimib/unimibmodules/dto/QuestionDTO.java
  src/main/java/it/unimib/unimibmodules/factory/QuestionFactory.java
  src/main/java/it/unimib/unimibmodules/model/Answer.java
  src/main/java/it/unimib/unimibmodules/model/Question.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionRepository.java
  src/main/java/it/unimib/unimibmodules/repository/Repository.java
Labels: enhancement

#23 Implementation User
  src/main/java/it/unimib/unimibmodules/controller/DTOMapping.java
  src/main/java/it/unimib/unimibmodules/controller/UserController.java
  src/main/java/it/unimib/unimibmodules/dao/UserDAO.java
  src/main/java/it/unimib/unimibmodules/dto/UserDTO.java
  src/main/java/it/unimib/unimibmodules/factory/UserFactory.java
  src/main/java/it/unimib/unimibmodules/model/User.java
  src/main/java/it/unimib/unimibmodules/repository/UserRepository.java
Labels: enhancement

#24 Implementation Survey
  pom.xml
  src/main/java/it/unimib/unimibmodules/UnimibModulesApplication.java
  src/main/java/it/unimib/unimibmodules/controller/DTOMapping.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyController.java
  src/main/java/it/unimib/unimibmodules/dao/SurveyDAO.java
  src/main/java/it/unimib/unimibmodules/dto/SurveyDTO.java
  src/main/java/it/unimib/unimibmodules/exception/SurveyException.java
  src/main/java/it/unimib/unimibmodules/factory/SurveyFactory.java
  src/main/java/it/unimib/unimibmodules/model/Survey.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyRepository.java
Labels: enhancement

#33 Implemented QuestionController's methods
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/dao/QuestionDAO.java
  src/main/java/it/unimib/unimibmodules/dto/QuestionDTO.java
  src/main/java/it/unimib/unimibmodules/dto/UserDTO.java
  src/main/java/it/unimib/unimibmodules/model/Question.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionRepository.java
Labels: enhancement

#31 Implemented AnswerController methods
  pom.xml
  src/main/java/it/unimib/unimibmodules/controller/AnswerController.java
  src/main/java/it/unimib/unimibmodules/controller/CloseEndedAnswerController.java
  src/main/java/it/unimib/unimibmodules/dao/AnswerDAO.java
  src/main/java/it/unimib/unimibmodules/dao/CloseEndedAnswerDAO.java
  src/main/java/it/unimib/unimibmodules/dto/AnswerDTO.java
  src/main/java/it/unimib/unimibmodules/dto/CloseEndedAnswerDTO.java
  src/main/java/it/unimib/unimibmodules/dto/QuestionDTO.java
  src/main/java/it/unimib/unimibmodules/dto/SurveyDTO.java
  src/main/java/it/unimib/unimibmodules/factory/AnswerFactory.java
  src/main/java/it/unimib/unimibmodules/model/Answer.java
  src/main/java/it/unimib/unimibmodules/model/CloseEndedAnswer.java
  src/main/java/it/unimib/unimibmodules/model/Question.java
  src/main/java/it/unimib/unimibmodules/repository/AnswerRepository.java
  src/main/java/it/unimib/unimibmodules/repository/CategoryRepository.java
  src/main/java/it/unimib/unimibmodules/repository/CloseEndedAnswerRepository.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionRepository.java
  src/main/java/it/unimib/unimibmodules/repository/Repository.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyRepository.java
  src/main/java/it/unimib/unimibmodules/repository/UserRepository.java
  src/main/resources/application.properties
  src/test/java/it/unimib/unimibmodules/model/AnswerTest.java
Labels: enhancement

#34 Implementation Category
  src/main/java/it/unimib/unimibmodules/controller/CategoryController.java
  src/main/java/it/unimib/unimibmodules/dao/CategoryDAO.java
  src/main/java/it/unimib/unimibmodules/dto/CategoryDTO.java
  src/main/java/it/unimib/unimibmodules/repository/CategoryRepository.java
Labels: enhancement

#35 Implemented UserController Class
  pom.xml
  src/main/java/it/unimib/unimibmodules/controller/UserController.java
  src/main/java/it/unimib/unimibmodules/dao/UserDAO.java
  src/main/java/it/unimib/unimibmodules/dto/UserDTO.java
  src/main/java/it/unimib/unimibmodules/factory/UserFactory.java
  src/main/java/it/unimib/unimibmodules/model/User.java
  src/main/java/it/unimib/unimibmodules/repository/Repository.java
  src/main/java/it/unimib/unimibmodules/repository/UserRepository.java
Labels: enhancement

#43 Added question and survey search
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/controller/QuestionRepository.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyController.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyRepository.java
  src/main/java/it/unimib/unimibmodules/controller/ViewController.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionDAO.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyDAO.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyRepositoryImpl.java
  src/main/resources/static/controller/searchQuestionCtrl.js
  src/main/resources/static/controller/searchSurveyCtrl.js
  src/main/resources/static/searchQuestion.html
  src/main/resources/static/searchSurvey.html
Labels: enhancement

#44 Survey UI implementation
  .github/workflows/build.yml
  pom.xml
  src/main/java/it/unimib/unimibmodules/controller/CategoryController.java
  src/main/java/it/unimib/unimibmodules/controller/CategoryRepository.java
  src/main/java/it/unimib/unimibmodules/controller/CloseEndedAnswerController.java
  src/main/java/it/unimib/unimibmodules/controller/DTOMapping.java
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/controller/QuestionRepository.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyController.java
  src/main/java/it/unimib/unimibmodules/controller/UserController.java
  src/main/java/it/unimib/unimibmodules/dto/QuestionDTO.java
  src/main/java/it/unimib/unimibmodules/dto/SurveyDTO.java
  src/main/java/it/unimib/unimibmodules/exception/ExceptionController.java
  src/main/java/it/unimib/unimibmodules/exception/FormatException.java
  src/main/java/it/unimib/unimibmodules/exception/NotFoundException.java
  src/main/java/it/unimib/unimibmodules/model/CloseEndedAnswer.java
  src/main/java/it/unimib/unimibmodules/model/Question.java
  src/main/java/it/unimib/unimibmodules/model/QuestionType.java
  src/main/java/it/unimib/unimibmodules/model/Survey.java
  src/main/java/it/unimib/unimibmodules/repository/CategoryRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionRepositoryImpl.java
  src/main/resources/static/add-survey/add-survey.component.js
  src/main/resources/static/add-survey/add-survey.module.js
  src/main/resources/static/add-survey/add-survey.template.html
  src/main/resources/static/add_Question.html
  src/main/resources/static/app.config.js
  src/main/resources/static/app.module.js
  src/main/resources/static/compile-survey/compile-survey.component.js
  src/main/resources/static/compile-survey/compile-survey.module.js
  src/main/resources/static/compile-survey/compile-survey.template.html
  src/main/resources/static/controller/addQuestionCtrl.js
  src/main/resources/static/controller/app.js
  src/main/resources/static/controller/editQuestionCtrl.js
  src/main/resources/static/controller/selectQuestionCtrl.js
  src/main/resources/static/edit_Question.html
  src/main/resources/static/find-survey/find-survey.component.js
  src/main/resources/static/find-survey/find-survey.module.js
  src/main/resources/static/find-survey/find-survey.template.html
  src/main/resources/static/index.html
  src/main/resources/static/modify-survey/modify-survey.component.js
  src/main/resources/static/modify-survey/modify-survey.module.js
  src/main/resources/static/modify-survey/modify-survey.template.html
  src/main/resources/static/package.json
  src/main/resources/static/select_Question.html
  src/main/resources/static/styles/survey.css
  src/main/resources/static/yarn.lock
Labels: enhancement

#45 Implementation User UI
  src/main/java/it/unimib/unimibmodules/controller/UserController.java
  src/main/java/it/unimib/unimibmodules/dto/UserDTO.java
  src/main/resources/static/controller/getUserCtrl.js
  src/main/resources/static/controller/logInUserCtrl.js
  src/main/resources/static/controller/signUpUserCtrl.js
  src/main/resources/static/login.html
  src/main/resources/static/signup.html
Labels: enhancement

#46 Implementation Question UI
  src/main/java/it/unimib/unimibmodules/controller/CloseEndedAnswerController.java
  src/main/java/it/unimib/unimibmodules/controller/DTOMapping.java
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/controller/ViewController.java
  src/main/java/it/unimib/unimibmodules/model/Question.java
  src/main/resources/static/controller/editQuestionCtrl.js
Labels: enhancement

#49 Corrected code smells
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyController.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyRepository.java
  src/main/java/it/unimib/unimibmodules/exception/EmptyCategoryException.java
  src/main/java/it/unimib/unimibmodules/model/Category.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyDAO.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyRepositoryImpl.java
Labels: enhancement

#51 Implemented Angular routing, fixed code smells, updated front-end user operations.
  src/main/java/it/unimib/unimibmodules/controller/UserController.java
  src/main/java/it/unimib/unimibmodules/dto/UserDTO.java
  src/main/java/it/unimib/unimibmodules/factory/UserFactory.java
  src/main/java/it/unimib/unimibmodules/model/User.java
  src/main/resources/static/app.config.js
  src/main/resources/static/app.module.js
  src/main/resources/static/controller/logInUserCtrl.js
  src/main/resources/static/controller/sessionService.js
  src/main/resources/static/controller/signUpUserCtrl.js
  src/main/resources/static/cookies/cookies.component.js
  src/main/resources/static/cookies/cookies.module.js
  src/main/resources/static/cookies/cookies.template.html
  src/main/resources/static/get-user/get-user.component.js
  src/main/resources/static/get-user/get-user.module.js
  src/main/resources/static/get-user/get-user.template.html
  src/main/resources/static/index.html
  src/main/resources/static/login-user/login-user.component.js
  src/main/resources/static/login-user/login-user.module.js
  src/main/resources/static/login-user/login-user.template.html
  src/main/resources/static/login.html
  src/main/resources/static/signup-user/signup-user.component.js
  src/main/resources/static/signup-user/signup-user.module.js
  src/main/resources/static/signup-user/signup-user.template.html
  src/main/resources/static/signup.html
Labels: enhancement

#52 Updated Question UI
  src/main/java/it/unimib/unimibmodules/controller/CategoryRepository.java
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/controller/QuestionRepository.java
  src/main/java/it/unimib/unimibmodules/dto/QuestionDTO.java
  src/main/java/it/unimib/unimibmodules/dto/SurveyDTO.java
  src/main/java/it/unimib/unimibmodules/dto/SurveyQuestionsDTO.java
  src/main/java/it/unimib/unimibmodules/model/Question.java
  src/main/java/it/unimib/unimibmodules/model/Survey.java
  src/main/java/it/unimib/unimibmodules/model/SurveyQuestions.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionDAO.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionRepositoryImpl.java
  src/main/resources/static/add-question/add-question.component.js
  src/main/resources/static/add-question/add-question.module.js
  src/main/resources/static/add-question/add-question.template.html
  src/main/resources/static/add_Question.html
  src/main/resources/static/app.config.js
  src/main/resources/static/app.module.js
  src/main/resources/static/controller/addQuestionCtrl.js
  src/main/resources/static/controller/editQuestionCtrl.js
  src/main/resources/static/edit-question/edit-question.component.js
  src/main/resources/static/edit-question/edit-question.module.js
  src/main/resources/static/edit-question/edit-question.template.html
  src/main/resources/static/edit_Question.html
  src/main/resources/static/index.html
Labels: enhancement

#59 Implementation Cookies, Auth and Logout
  pom.xml
  src/main/java/it/unimib/unimibmodules/controller/UserController.java
  src/main/java/it/unimib/unimibmodules/controller/UserRepository.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/repository/UserRepositoryImpl.java
  src/main/resources/static/add-survey/add-survey.component.js
  src/main/resources/static/app.config.js
  src/main/resources/static/app.module.js
  src/main/resources/static/controller/authService.js
  src/main/resources/static/controller/cookieService.js
  src/main/resources/static/controller/getUserCtrl.js
  src/main/resources/static/controller/homeCtrl.js
  src/main/resources/static/controller/logoutUserCtrl.js
  src/main/resources/static/controller/sessionService.js
  src/main/resources/static/cookies/cookies.component.js
  src/main/resources/static/cookies/cookies.module.js
  src/main/resources/static/cookies/cookies.template.html
  src/main/resources/static/get-user/get-user.component.js
  src/main/resources/static/home/home.component.js
  src/main/resources/static/home/home.module.js
  src/main/resources/static/index.html
  src/main/resources/static/login-user/login-user.component.js
  src/main/resources/static/signup-user/signup-user.template.html
  src/main/resources/static/styles/style.css
  src/main/resources/static/template/home.html
Labels: enhancement

#63 Sending email when the user completes a survey, merged compile survey and edit survey answers and Unit of Work improvements
  .github/workflows/build.yml
  pom.xml
  src/main/java/it/unimib/unimibmodules/Service/MailServiceImpl.java
  src/main/java/it/unimib/unimibmodules/controller/AnswerController.java
  src/main/java/it/unimib/unimibmodules/controller/AnswerRepository.java
  src/main/java/it/unimib/unimibmodules/controller/MailService.java
  src/main/java/it/unimib/unimibmodules/repository/AnswerRepositoryImpl.java
  src/main/resources/static/app.config.js
  src/main/resources/static/app.module.js
  src/main/resources/static/compile-survey/compile-survey.component.js
  src/main/resources/static/compile-survey/compile-survey.template.html
  src/main/resources/static/edit-survey-answer/edit-survey-answer.component.js
  src/main/resources/static/edit-survey-answer/edit-survey-answer.module.js
  src/main/resources/static/edit-survey-answer/edit-survey-answer.template.html
  src/main/resources/static/factory/AnswerFactory.js
  src/main/resources/static/index.html
Labels: enhancement

#66 Implemented Lazy Loading
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/controller/QuestionRepository.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyController.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyRepository.java
  src/main/java/it/unimib/unimibmodules/dto/SurveyDTO.java
  src/main/java/it/unimib/unimibmodules/exception/ExceptionController.java
  src/main/java/it/unimib/unimibmodules/factory/SurveyFactory.java
  src/main/java/it/unimib/unimibmodules/model/Survey.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionDAO.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyDAO.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyQuestionsDAO.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyRepositoryImpl.java
  src/main/resources/static/add-survey/add-survey.component.js
  src/main/resources/static/home/home.component.js
  src/main/resources/static/home/home.template.html
  src/main/resources/static/modify-survey/modify-survey.component.js
  src/main/resources/static/modify-survey/modify-survey.template.html
  src/main/resources/static/styles/survey.css
  src/test/java/it/unimib/unimibmodules/model/SurveyTest.java
Labels: enhancement

#68 Implemented images' operations
  .github/workflows/build.yml
  pom.xml
  src/main/java/it/unimib/unimibmodules/controller/AWSToken.java
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/service/AWSTokenImpl.java
  src/main/resources/static/add-question/add-question.component.js
  src/main/resources/static/edit-question/edit-question.component.js
  src/main/resources/static/edit-question/edit-question.template.html
  src/main/resources/static/index.html
  src/main/resources/static/package.json
  src/main/resources/static/service/awsService.js
  src/main/resources/static/yarn.lock
Labels: enhancement

#70 Replaced explicit getters and setters with Lombok
  pom.xml
  src/main/java/it/unimib/unimibmodules/controller/AnswerController.java
  src/main/java/it/unimib/unimibmodules/dto/AnswerDTO.java
  src/main/java/it/unimib/unimibmodules/dto/CategoryDTO.java
  src/main/java/it/unimib/unimibmodules/dto/CloseEndedAnswerDTO.java
  src/main/java/it/unimib/unimibmodules/dto/QuestionDTO.java
  src/main/java/it/unimib/unimibmodules/dto/SurveyDTO.java
  src/main/java/it/unimib/unimibmodules/dto/SurveyQuestionsDTO.java
  src/main/java/it/unimib/unimibmodules/dto/UserDTO.java
  src/main/java/it/unimib/unimibmodules/model/Answer.java
  src/main/java/it/unimib/unimibmodules/model/Category.java
  src/main/java/it/unimib/unimibmodules/model/CloseEndedAnswer.java
  src/main/java/it/unimib/unimibmodules/model/Question.java
  src/main/java/it/unimib/unimibmodules/model/Survey.java
  src/main/java/it/unimib/unimibmodules/model/SurveyQuestions.java
  src/main/java/it/unimib/unimibmodules/model/User.java
Labels: enhancement

#71 Added cookieservice in Question and fixed code smells
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/controller/UserController.java
  src/main/java/it/unimib/unimibmodules/factory/QuestionFactory.java
  src/main/java/it/unimib/unimibmodules/model/Question.java
  src/main/java/it/unimib/unimibmodules/repository/UserRepositoryImpl.java
  src/main/resources/static/add-question/add-question.component.js
  src/main/resources/static/edit-question/edit-question.component.js
  src/main/resources/static/home/home.template.html
Labels: enhancement

#72 Implemented AWS API for questions images in modify survey
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyController.java
  src/main/java/it/unimib/unimibmodules/model/Survey.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyRepositoryImpl.java
  src/main/resources/static/add-survey/add-survey.component.js
  src/main/resources/static/add-survey/add-survey.template.html
  src/main/resources/static/home/home.component.js
  src/main/resources/static/modify-survey/modify-survey.component.js
  src/main/resources/static/modify-survey/modify-survey.template.html
Labels: enhancement

#74 Enhancement pdf generation
  .github/workflows/build.yml
  pom.xml
  src/main/java/it/unimib/unimibmodules/controller/AWSToken.java
  src/main/java/it/unimib/unimibmodules/controller/AnswerController.java
  src/main/java/it/unimib/unimibmodules/controller/PdfService.java
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/service/AWSTokenImpl.java
  src/main/java/it/unimib/unimibmodules/service/PdfServiceImpl.java
Labels: enhancement

#75 Implementation of navbar buttons and cookies
  src/main/java/it/unimib/unimibmodules/controller/UserController.java
  src/main/java/it/unimib/unimibmodules/factory/UserFactory.java
  src/main/java/it/unimib/unimibmodules/model/User.java
  src/main/resources/static/add-question/add-question.component.js
  src/main/resources/static/add-question/add-question.template.html
  src/main/resources/static/add-survey/add-survey.component.js
  src/main/resources/static/add-survey/add-survey.template.html
  src/main/resources/static/app.config.js
  src/main/resources/static/compile-survey/compile-survey.component.js
  src/main/resources/static/compile-survey/compile-survey.template.html
  src/main/resources/static/controller/navbarCtrl.js
  src/main/resources/static/edit-question/edit-question.component.js
  src/main/resources/static/edit-question/edit-question.template.html
  src/main/resources/static/get-user/get-user.component.js
  src/main/resources/static/get-user/get-user.template.html
  src/main/resources/static/home/home.component.js
  src/main/resources/static/home/home.template.html
  src/main/resources/static/index.html
  src/main/resources/static/login-user/login-user.component.js
  src/main/resources/static/login-user/login-user.template.html
  src/main/resources/static/modify-survey/modify-survey.component.js
  src/main/resources/static/modify-survey/modify-survey.template.html
  src/main/resources/static/service/cookieService.js
  src/main/resources/static/signup-user/signup-user.component.js
  src/main/resources/static/signup-user/signup-user.template.html
  src/main/resources/static/styles/style.css
  src/main/resources/static/template/navbar.template.html
  src/test/java/it/unimib/unimibmodules/model/UserTest.java
Labels: enhancement

#77 Improved survey compilation and modification pages
  src/main/java/it/unimib/unimibmodules/controller/AnswerController.java
  src/main/java/it/unimib/unimibmodules/controller/CategoryRepositoryReadOnly.java
  src/main/java/it/unimib/unimibmodules/controller/CloseEndedAnswerController.java
  src/main/java/it/unimib/unimibmodules/controller/CloseEndedAnswerRepositoryReadOnly.java
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/controller/QuestionRepositoryReadOnly.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyController.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyRepositoryReadOnly.java
  src/main/java/it/unimib/unimibmodules/controller/UserRepositoryReadOnly.java
  src/main/java/it/unimib/unimibmodules/dto/CloseEndedAnswerDTO.java
  src/main/java/it/unimib/unimibmodules/factory/AnswerFactory.java
  src/main/java/it/unimib/unimibmodules/factory/QuestionFactory.java
  src/main/java/it/unimib/unimibmodules/factory/SurveyFactory.java
  src/main/java/it/unimib/unimibmodules/factory/UserFactory.java
  src/main/java/it/unimib/unimibmodules/repository/AnswerRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/repository/CategoryRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/repository/CloseEndedAnswerRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/repository/UnitOfWork.java
  src/main/java/it/unimib/unimibmodules/repository/UnitOfWorkOperations.java
  src/main/java/it/unimib/unimibmodules/repository/UserRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/service/MailServiceImpl.java
  src/main/resources/static/add-question/add-question.component.js
  src/main/resources/static/add-survey/add-survey.component.js
  src/main/resources/static/app.config.js
  src/main/resources/static/compile-survey/compile-survey.component.js
  src/main/resources/static/compile-survey/compile-survey.template.html
  src/main/resources/static/edit-question/edit-question.component.js
  src/main/resources/static/get-user/get-user.component.js
  src/main/resources/static/home/home.component.js
  src/main/resources/static/login-user/login-user.component.js
  src/main/resources/static/service/cookieService.js
  src/main/resources/static/template/download-survey.template.html
  src/test/java/it/unimib/unimibmodules/model/AnswerTest.java
Labels: enhancement

#79 Fixed various bugs
  src/main/java/it/unimib/unimibmodules/service/PdfServiceImpl.java
  src/main/resources/static/add-question/add-question.component.js
  src/main/resources/static/add-survey/add-survey.component.js
  src/main/resources/static/app.config.js
  src/main/resources/static/compile-survey/compile-survey.component.js
  src/main/resources/static/edit-question/edit-question.component.js
  src/main/resources/static/get-user/get-user.component.js
  src/main/resources/static/home/home.component.js
  src/main/resources/static/index.html
  src/main/resources/static/login-user/login-user.component.js
  src/main/resources/static/modify-survey/modify-survey.component.js
  src/main/resources/static/signup-user/signup-user.component.js
Labels: bug

#80 Implementation of Bootstrap Modals
  README.md
  src/main/resources/static/add-question/add-question.component.js
  src/main/resources/static/add-survey/add-survey.component.js
  src/main/resources/static/compile-survey/compile-survey.component.js
  src/main/resources/static/edit-question/edit-question.component.js
  src/main/resources/static/get-user/get-user.component.js
  src/main/resources/static/home/home.component.js
  src/main/resources/static/login-user/login-user.component.js
  src/main/resources/static/login-user/login-user.template.html
  src/main/resources/static/modify-survey/modify-survey.component.js
  src/main/resources/static/signup-user/signup-user.component.js
  src/main/resources/static/signup-user/signup-user.template.html
  src/main/resources/static/template/navbar.template.html
Labels: enhancement

#81 General fixes
  src/main/java/it/unimib/unimibmodules/controller/QuestionController.java
  src/main/java/it/unimib/unimibmodules/controller/QuestionRepository.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyController.java
  src/main/java/it/unimib/unimibmodules/exception/ExceptionController.java
  src/main/java/it/unimib/unimibmodules/model/Survey.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionDAO.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyDAO.java
  src/main/resources/static/home/home.component.js
  src/main/resources/static/index.html
  src/main/resources/static/modify-survey/modify-survey.component.js
  src/main/resources/static/modify-survey/modify-survey.template.html
  src/main/resources/static/template/navbar.template.html
Labels: enhancement

#82 Various fixes and improvements
  src/main/java/it/unimib/unimibmodules/controller/UserController.java
  src/main/java/it/unimib/unimibmodules/service/PdfServiceImpl.java
  src/main/resources/static/compile-survey/compile-survey.template.html
Labels: bug, enhancement

#83 Fix some bugs in addQuestion, editQuestion and SurveyController
  src/main/java/it/unimib/unimibmodules/controller/SurveyController.java
  src/main/resources/static/add-question/add-question.component.js
  src/main/resources/static/edit-question/edit-question.component.js
  src/main/resources/static/service/awsService.js
Labels: bug

#84 Implemented compile by code functionality
  src/main/java/it/unimib/unimibmodules/controller/SurveyController.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyRepository.java
  src/main/java/it/unimib/unimibmodules/controller/UserRepository.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyDAO.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/repository/UserRepositoryImpl.java
  src/main/resources/static/home/home.component.js
  src/main/resources/static/home/home.template.html
Labels: enhancement

#85 Fixed small code smells
  src/main/java/it/unimib/unimibmodules/repository/SurveyRepositoryImpl.java
Labels: enhancement

#86 Fixed Logout Bug and Code Smell
  src/main/java/it/unimib/unimibmodules/controller/SurveyController.java
  src/main/java/it/unimib/unimibmodules/controller/SurveyRepository.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyDAO.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/service/AWSTokenImpl.java
  src/main/resources/static/compile-survey/compile-survey.component.js
  src/main/resources/static/get-user/get-user.component.js
  src/main/resources/static/get-user/get-user.template.html
  src/main/resources/static/home/home.component.js
Labels: bug, enhancement

#87 Various fix and improvements + created some project files
  AUTHORS.md
  CHANGELOG.md
  README.md
  src/main/java/it/unimib/unimibmodules/controller/UserController.java
  src/main/java/it/unimib/unimibmodules/exception/SurveyException.java
  src/main/java/it/unimib/unimibmodules/model/Answer.java
  src/main/java/it/unimib/unimibmodules/model/Question.java
  src/main/java/it/unimib/unimibmodules/model/User.java
  src/main/java/it/unimib/unimibmodules/repository/QuestionRepositoryImpl.java
  src/main/java/it/unimib/unimibmodules/repository/SurveyRepositoryImpl.java
  src/main/resources/static/compile-survey/compile-survey.component.js
  src/main/resources/static/login-user/login-user.template.html
  src/main/resources/static/modify-survey/modify-survey.template.html
  src/main/resources/static/signup-user/signup-user.template.html
  src/main/resources/static/template/navbar.template.html
  src/test/java/it/unimib/unimibmodules/UnimibModulesApplicationTests.java
Labels: bug, documentation, enhancement

#89 Various fixes and updated README
  README.md
  sql/unimibdb.sql
  src/main/java/it/unimib/unimibmodules/controller/AnswerController.java
  src/main/java/it/unimib/unimibmodules/controller/PdfService.java
  src/main/java/it/unimib/unimibmodules/controller/UserController.java
  src/main/java/it/unimib/unimibmodules/service/PdfServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/compile-survey/compile-survey.component.js
Labels: bug, documentation, enhancement
